apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: production
  name: greeting-service
spec:
  selector:
    matchLabels:
      environment: production
  template:
    metadata:
      labels:
        environment: production
    spec:
      containers:
        - name: app
          env:
            - name: LOG_LEVEL
              value: DEBUG

patches:
  - path: deployment.yaml
