---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: deployment.yaml
  - target:
      kind: GRPCRoute
      name: greeting-service-route
    patch: |-
      - op: add
        path: /spec/rules/0/matches/0/headers
        value:
          values:
            x-subdomain: sandbox
      - op: add
        path: /spec/rules/-
        value:
          matches:
            - method:
                service: grpc.reflection.v1.ServerReflection
          backendRefs:
            - name: greeting-service
              port: 50051
  - target:
      kind: Service
      name: greeting-service
    patch: |-
      - op: add
        path: /spec/selector/environment
        value: local
